### ISSUE TITLE
Adding Array of items as prop, set default value to [...] similar to function

### ISSUE THREAD

**Issue by ChrisSki** [alansouzati/jsx-to-string#6]
I'm passing in an array of items and it prints out the entire thing which makes it look a bit crazy. I modified the code to act similarly to a function being passed in as a prop. If you'd like me to submit a PR, I'd be happy to.

**Comment by alansouzati** [comment]
Can you add here how your array looks like on you print them?

If I remember correctly, I added JSON formatting for such cases so that it prints in a readable manner.

When I wrote this library my idea was to allow for copy and paste a code snippet and get it working pretty much right of the bet. Unfortunately functions are tricky to translate. Generally speaking, arrays should work just fine.

**Comment by ChrisSki** [comment]
@alansouzati sorry for the confusion. The array of objects look fine. I was simply looking to add a placeholder similar to what you use for functions.

I am using this tool to pass the string to codemirror, which in turn displays the component with array of items as the prop value. Since I am using the code for a style guide, I don't necessarily need to show an entire array of items. Just what type is being passed in as  a prop.

Hopefully I explained that properly. If this doesn't make sense for your tool, I totally understand. Might just be an edge case. I can add screenshots if needed.

**Comment by alansouzati** [comment]
This feels like an edge case to me.

Have you tried using `keyValueOverride` to replace the value of your array to `...` ?

**Comment by ChrisSki** [comment]
Agreed. I'll use the keyValueOverride. Just more work ;)

**Comment by alansouzati** [comment]
Cool, im going to close the issue. Feel free to reopen if something else comes up.
